<!DOCTYPE HTML>
<html>
<head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
<title>Scrumie</title>
<script type="text/javascript" src="./layout/jquery.min.js"></script>
<script type="text/javascript" src="./layout/jquery-ui.min.js"></script>
<script type="text/javascript" src="./layout/scrumie.js"></script>
<link href="./layout/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" >

<style type="text/css">
    body {font-size: 11px; padding: 0; background: darkgray;}
</style>

</head>
<body>
<?= $this->content; ?>
</body>
</html>
