<!DOCTYPE HTML>
<html>
<head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
<meta name="google-site-verification" content="dXuZYAWNzllX1ocaNDSDtYN_ib9Qa8wfGa9pJBUtyMQ" />
<title>Scrumie</title>
<link href="./layout/jquery/css/redmond/jquery-ui-1.8.10.custom.css" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript" src="./layout/jquery/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="./layout/jquery/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" src="./layout/scrumie.js"></script>
<script type="text/javascript" src="./layout/google.wa.js"></script>

<style type="text/css">
    body {font-size: 11px; padding: 0; background: darkgray;}
</style>

</head>
<body>
<?= $this->content; ?>
</body>
</html>
