<!DOCTYPE HTML>
<html>
<head>
<meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
    <title>Scrumie</title>
    <link href="./layout/jquery/css/redmond/jquery-ui-1.8.10.custom.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="./layout/scrumie.css" media="screen" rel="stylesheet" type="text/css" >
    <script src="./layout/jquery/js/jquery-1.4.4.min.js"></script>
    <script src="./layout/jquery/js/jquery-ui-1.8.10.custom.min.js"></script>
    <script src="./layout/jquery.contextmenu.js"></script>
    <script src="./layout/scrumie.js"></script>
    <script src="./layout/highcharts.js"></script>
    <script src="./layout/google.wa.js"></script>
</head>
<body class="logged">
    <?= $this->content; ?>
</body>
</html>
