<?php
function prepareTask(Task $task, $draggable = true) {

    if($task->estimation === null)
        $task->estimation = 1;

    if($task->done === null)
        $task->done = 0;

    $draggable = ($draggable) ? 'draggable' : '';

    $taskHelper = '
        <div id="%s" class="task round4 %s">
            <div class="editable body">%s</div>
            <span title="Estimation" class="estimation">%s</span>
            &nbsp;
            <span title="Done" class="done">%s</span>
            &nbsp;
            <span class="owner" title="Owner" style="float: right;">%s</span>
        </div>';

    return sprintf($taskHelper, $task->id, $draggable, $task->body, $task->estimation, $task->done, $task->owner);
}
?>

<div id="tabs">
    <ul>
        <li><a href="#tabs-sprints">Sprints</a></li>
        <li><a href="#tabs-board">Board</a></li>
        <li><a href="#tabs-burndownchart">Burn down chart</a></li>
        <li><a href="#tabs-backlog">Backlog</a></li>
        <li><a onclick="location.href = '?controller=Project&action=logout'">Logout</a></li>
    </ul>

    <div id="tabs-board" class="tabContent">
        <div class="helpers">
            <button onclick="addNewTask();">+ Add new task</button>
            <div id="sprintTitle"><?= $this->sprintName; ?></div>
        </div>
        <table id="board" class="round4">
            <tr>
                <th>
                    TODO
                    <div class="summary">
                        <span id="todo-sum-done">0</span>
                        /
                        <span id="todo-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    IN PROGRESS
                    <div class="summary">
                        <span id="inProgress-sum-done">0</span>
                        /
                        <span id="inProgress-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    COMMITED
                    <div class="summary">
                        <span id="commited-sum-done">0</span>
                        /
                        <span id="commited-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    READY FOR TEST
                    <div class="summary">
                        <span id="readyForTest-sum-done">0</span>
                        /
                        <span id="readyForTest-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    DONE
                    <div class="summary">
                        <span id="done-sum-done">0</span>
                        /
                        <span id="done-sum-estimation">0</span>
                    </div>
                </th>
            </tr>
            <tr>
                <td id="todo" class="droppable">
                <?php
                    foreach($this->tasks['todo'] as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="inProgress" class="droppable">
                <?php
                    foreach($this->tasks['inProgress'] as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="commited" class="droppable">
                <?php
                    foreach($this->tasks['commited'] as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="readyForTest" class="droppable">
                <?php
                    foreach($this->tasks['readyForTest'] as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="done" class="droppable">
                <?php
                    foreach($this->tasks['done'] as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
            </tr>
        </table>

    </div>

    <div id="tabs-sprints" class="tabContent">
    <button onclick="addNewSprint()">+ Add new sprint</button>
    <ul id="sprints-list">
        <?php
        foreach($this->sprints as $sprint) {
            echo sprintf('<li><a href="?controller=Board&sprint=%s">%s</a></li>', $sprint->id, $sprint->name);
        }
        ?>
    </ul>
    </div>

    <div id="tabs-burndownchart" class="tabContent">
    <button onclick="reloadBtc()">Redraw</button>
    <div style="width: 90%" id="burndownchart-container"></div>
    <script>
        var chart;
        $(document).ready(function() {
           chart = new Highcharts.Chart({
              chart: {
                 renderTo: 'burndownchart-container'
              },
              xAxis: {
                categories: [<?= $this->btc_x_categories?>]
              },
              yAxis: {
                 title: {text: 'Estimation points'},
                 min: 0,
                 max: <?= $this->btc_y_max ?>,
              },
              title: {
                 text: 'Burndown chart'
              },
              tooltip: { formatter: function() { return this.y +' points' } },
              series: [{
                 name: 'Points left',
                 data: [<?= $this->btc_series ?>],
                 marker: {
                    radius: 4
                 }
              }]
           });
        });

        function reloadBtc() {
            location.href = location.href.replace(/&tab.*/, '') + '&tab=2';
        }
    </script>
    </div>

    <div id="tabs-backlog" class="tabContent">
        <button onclick="addNewBacklogTask();">+ Add new task</button>
        <div class="sortable" id="detached">
            <?php
                foreach($this->detached as $task) {
                    echo prepareTask($task, false);
                }
            ?>
        </div>
    </div>
</div>

<!-- task context menu -->
<div class="contextMenu" id="taskMenu">
    <ul>
        <li id="task_estimate">Estimate</li>
        <li id="task_done">Set done</li>
        <li id="task_setOwner">Set owner</li>
        <li><hr/></li>
        <li id="task_attach">Move to sprint</li>
        <li id="task_detach">Move&nbsp;to&nbsp;backlog</li>
        <li><hr/></li>
        <li id="task_delete">Delete</li>
    </ul>
</div>

<script>
function setDraggable() {
    $(".draggable").draggable({
        stop: function(event, ui) {
            $(this).css('top', 0);
            $(this).css('left', 0);
        }
    });

    $(".draggable").css('cursor', 'move');
}

function setSortable() {
    $(".sortable").sortable({
        stop: function() {
            var order = new Array;
            $.each($(this).children('div.task'), function(index, element) {
                order[index] = $(element).attr('id');
            });

            $.post('?controller=Board&action=reorderTask', {'order': order}, function(data, status, Request) {
            });
        }
    });
}

function setEditable() {

    $.each($('.editable'), function(index, element) {
        $(element).unbind();
    });

    $('.task').contextMenu("taskMenu", {
        shadow: true, 
        menuStyle: {
            width: '150px'
        },
        onShowMenu: function(e, menu) {
            var parent = $(e.currentTarget).parent();
            if($(parent).attr('id') == 'detached') {
                $('#task_detach', menu).remove();
            }
            else {
                $('#task_attach', menu).remove();
            }

            return menu;
        },
        bindings: {
            'task_estimate': function(t) {
                var value = prompt('Please enter estimation value');

                if(value === null)
                    return;

                if( value.match(/[^0-9]+/) )
                    alert('Estimation must be number');
                else
                    $(t).children('span.estimation').html(value);

                saveTask(t);
            },
            'task_done': function(t) {
                var value = prompt('Please enter value');

                if(value === null)
                    return;

                if( value.match(/[^0-9]+/) )
                    alert('It must be number');
                else
                    $(t).children('span.done').html(value);

                saveTask(t);
            },
            'task_setOwner': function(t) {
                var value = prompt('Please enter onwer');

                if(value === null)
                    return;

                $(t).children('span.owner').html(value);

                saveTask(t);
            },
            'task_delete': function(t) {
                if (! confirm('Are you sure you want to delete this task') )
                    return;

                $.post('?controller=Board&action=deleteTask', {taskId: $(t).attr('id')}, function(data, status, Request) {
                        if(data)
                            $(t).remove();
                });
            },
            'task_attach': function(t) {
                var task = $(t).appendTo('td#todo');
                saveTask(task);
            },
            'task_detach': function(t) {
                var task = $(t).appendTo('div#detached');
                saveTask(task);
            },
        }
    });

    $.each($('.editable'), function(index, element) {
        $(element).dblclick(function() {
            $(this).parent().draggable('option', 'disabled', true);
            $(this).attr('contenteditable', true);
            $(this).parent().fadeTo('slow', 0.9);
            $(this).css('border', '2px solid red');
            $(this).focus();

            $(this).unbind('blur');
            $(this).unbind('focus');
$(this).blur(function () {
                saveTask($(this).parent());
            });

            $(this).focus(function () {
                //edit
            });
        });
    });
}

function saveTask(task) {
    $(task).draggable('option', 'disabled', false);
    $(task).fadeTo('slow', 1);
    var content = $(task).children('div.editable');
    $(content).attr('contenteditable', false);
    $(content).css('border', '0');

    var params = {
        taskId: $(task).attr('id'),
        body: $(content).html(),
        estimation: $(task).children('span.estimation').html(),
        done: $(task).children('span.done').html(),
        owner: $(task).children('span.owner').html(),
        sprintId: $.getUrlVar('sprint'),
        state: $(task).parent().attr('id')
    };

    $.post('?controller=Board&action=saveTask', params, function(data, status, Request) {
        if(data)
            $(task).attr('id', data)
        else
            alert('Problem with saving data');
    });

    updateSummary();
}

function addNewTask() {
    var taskHtml = '<div id="" class="task round4 draggable"><div class="editable body">Double click to edit...</div><span title="Estimation" class="estimation">1</span>&nbsp;<span class="done">0</span>&nbsp;<span class="owner" title="Owner" style="float: right;"></span></div>';
    var task = $(taskHtml).appendTo('td#todo');
    setEditable();
    setDraggable();
}

function addNewBacklogTask() {
    <?php
        $task = new Task;
        $task->estimation = 1;
        $task->done = 0;
        $task->body = 'Double click to edit...';
        $task->id = null;
        $task->owner = null;
    ?>
    var task = '<?= str_replace("\n", '' ,prepareTask($task, false)); ?>';
    $('#detached').append(task);
    setSortable();
    setEditable();
}

function addNewSprint() {
    var sprintName = prompt('Sprint name');

    if(sprintName == null)
        return

    if(sprintName == '') {
        alert('Sprint name can\'t be empty');
        addNewSprint();
    }
    else
    {
        $.post('?controller=Board&action=addNewSprint', {'sprintName': sprintName}, function(data, status, Request) {
            if(isNaN(parseInt(data)))
                alert(data)
            else
                location.href = '?controller=Board';
        });
    }
}

$(".droppable").droppable({
    drop: function(event,ui) {
        ui.helper.appendTo(this);
        setDraggable();
        saveTask(ui.helper);
    }
});


function updateSummary() {
    var summary = [];
    summary['todo'] = {all: 0, done: 0};
    summary['inProgress'] = {all: 0, done: 0};
    summary['commited'] = {all: 0, done: 0};
    summary['readyForTest'] = {all: 0, done: 0};
    summary['done'] = {all: 0, done: 0};

    $.each($('table#board td'), function(index,element) {
        var column = $(element).attr('id');

        var summaryEstimation = 0;
        $.each($(element).children('div.task').children('span.estimation'), function(i, e) {
            summaryEstimation += getAsNumber($(e).html());
        });

        var summaryDone = 0;
        $.each($(element).children('div.task').children('span.done'), function(i, e) {
            summaryDone += getAsNumber($(e).html());
        });

        summary[column].all = summaryEstimation;
        summary[column].done = summaryDone;

    });

    $('span#todo-sum-estimation').html(summary['todo'].all);
    $('span#todo-sum-done').html(summary['todo'].done);

    $('span#inProgress-sum-estimation').html(summary['todo'].all + summary['inProgress'].all);
    $('span#inProgress-sum-done').html(summary['inProgress'].done);
    
    $('span#commited-sum-estimation').html(summary['todo'].all + summary['inProgress'].all + summary['commited'].all);
    $('span#commited-sum-done').html(summary['commited'].done);

    $('span#readyForTest-sum-estimation').html(summary['todo'].all + summary['inProgress'].all + summary['commited'].all + summary['readyForTest'].all);
    $('span#readyForTest-sum-done').html(summary['readyForTest'].done);

    $('span#done-sum-estimation').html(summary['todo'].all + summary['inProgress'].all + summary['commited'].all + summary['readyForTest'].all + summary['done'].all);
    $('span#done-sum-done').html(summary['done'].done);
}


$(function() {
    $( "#tabs" ).tabs();

    var tabIndex = parseInt($.getUrlVar('tab'));
    if(tabIndex)
        $( "#tabs" ).tabs({ selected: parseInt(tabIndex) });
    else if($.getUrlVar('sprint')) 
        $( "#tabs" ).tabs({ selected: 1 });

    setDraggable();
    setEditable();
    setSortable();
    $("table#board").css('height', ($(window).height() - 120));

    updateSummary();

});

</script>
