<div id="tabs">
    <ul>
        <li><a href="#tabs-home"><img src="http://cdn1.iconfinder.com/data/icons/gnomeicontheme/16x16/actions/redhat-home.png"></a></li>
        <?php if(isset($this->project)): ?>
            <li><a href="#tabs-board">Board</a></li>
            <li><a href="#tabs-backlog">Backlog</a></li>
            <li><a href="#tabs-burndownchart">Burn down chart</a></li>
        <?php endif ?>
        <li><a id="logout">Logout</a></li>
    </ul>

    <!-- HOME -->
    <div id="tabs-home" class="tabContent">
        <p>Welcome! <strong><?= $this->user->login; ?></strong></p>
        <div id="columns">
            <div>
                <h1>Projects:</h1>
                <input id="new-project-name" type="text" placeholder="New project name"><button title="Add new project" onclick="Scrumie.Project.add($('#new-project-name').val())">+</button>
                <button title="Untouch/Delete project.&#13;Project will be deleted when no others contributors are assigned to it, otherwise it will be untouch only from your account" onclick="Scrumie.Project.del($('.projectName.selected'))">-</button>
                <ol>
                <?php 
                foreach($this->user->projects as $userProject) {
                    $project = $userProject->getProject();
                    $class = (isset($this->currentProjectId) && $project->id == $this->currentProjectId) ? 'selected' : '';
                    echo '<li data-projectId="'.$project->id.'" onclick="Scrumie.Project.select('.$project->id.')" class="projectName href '.$class.'">'.$project->name.'</li>';
                }
                ?>
                </ol>
            </div>
            <div>
                <h1>Contributors:</h1>
                <p>
                    <input id="new-contributor-name" type="text" placeholder="username">
                    <button title="Add new contributor" onclick="Scrumie.Project.addUser($('#new-contributor-name').val())">+</button>
                </p>
                <?php
                if($this->project) {
                    $contributors = array();
                    foreach($this->project->getUsers() as $projectUser) {
                        $user = $projectUser->getUser();
                        if($user->email) {
                            $contributors[] = '<a href="mailto:'.$user->email.'">'.$user->login.'</a>';
                        } else {
                            $contributors[] = '<span>'.$user->login.'</span>';
                        }
                    }
                    echo join(', ', $contributors);
                }
                ?>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>

    <!-- BACKLOG -->
    <?php if(isset($this->project)): ?>
    <div id="tabs-backlog" class="tabContent">
        <div class="sortable" id="detached">
        <?php
        foreach($this->project->getDetachedUserStories() as $story) {
            echo prepareUserStory($story, $project);
        }
        ?>
        </div>
        <button class="add_new_user_story">Add new User Story</button>
    </div>
    <?php endif ?>


    <!-- SPRINT -->
    <?php if(isset($this->project)): ?>
    <div id="tabs-board" class="tabContent">
        <div id="story-container">
            <table class="user_story header">
            <tr>
                <th>TODO<span class="summary todo"><em></em>/<em></em></span></th>
                <th>IN PROGRESS<span class="summary inProgress"><em></em>/<em></em></span></th>
                <th>TO VERIFY<span class="summary toVerify"><em></em>/<em></em></span></th>
                <th>DONE<span class="summary done"><em></em>/<em></em></span></th>
            </tr>
            </table>
            <?php foreach($this->project->getActiveUserStories() as $story): ?>
                <?= prepareUserStory($story, $project) ?>
            <?php endforeach ?>
        </div>
        <button class="add_new_user_story">Add new User Story</button>
    </div>
    <?php endif ?>

    <!-- BURN DOWN CHART -->
    <?php if(isset($this->project)): ?>
    <div id="tabs-burndownchart" class="tabContent">
        <button onclick="location.reload()">Redraw</button>
        <div style="width: 90%" id="burndownchart-container"></div>
        <script>
            $(document).ready(function() {
               var chart;
               chart = new Highcharts.Chart({
                  chart: {
                     renderTo: 'burndownchart-container'
                  },
                  xAxis: {
                    categories: [<?= '"'.join('","', $this->project->getTasks()->getAllTasksUpdateDates('D/d/M')).'"'; ?>]
                  },
                  yAxis: {
                     title: {text: 'Estimation points'},
                     min: 0,
                     max: <?= $this->project->getTasks()->getEstimationSum() ?>,
                  },
                  title: {
                     text: 'Burndown chart'
                  },
                  tooltip: { formatter: function() { return this.y +' points' } },
                  series: [{
                     name: 'Points left',
                     data: [<?= join(",", $this->project->getEstimationForEachDate()) ?>],
                     marker: {
                        radius: 4
                     }
                  }]
               });
            });
        </script>
    </div>
    <?php endif ?>
</div>

<?php if(isset($this->project)): ?>
    <div id="newtask" class="hidden">
        <?php echo prepareTask(new Task(), $this->project) ?>
    </div>

    <div id="newuserstory" class="hidden">
        <?= prepareUserStory(new Story(), $this->project) ?>
    </div>
<?php endif ?>

<script>
$(document).ready(function() {
    Scrumie.Board.refreshSummaryPoints();

    /**
     *  Events
     */
    (function() {
        $('#logout').click(function() {
            Scrumie.logout();
        });

        $('#story-container img.detach').live('click', function(event) {
            $(this).attr('title', 'Move to sprint');
            Scrumie.Story.detach($(this).parent().parent().parent().parent());
        });

        $('#detached img.detach').live('click', function(event) {
            $(this).attr('title', 'Move to sprint');
            Scrumie.Story.attach($(this).parent().parent().parent().parent());
        });

        $('img.delete_task').live('click', function(event) {
            event.stopPropagation();
            Scrumie.Task.del($(this).parent().parent(), function() {
                Scrumie.Sprint.refreshSummaryPoints();
            });
        });

        $('input.estimation').live('click', function(event) {
            event.stopPropagation();
        });

        $('input.estimation').live('change', function(event) {
            Scrumie.Task.save($(this).parent().parent()); 
            Scrumie.Story.recalculate($(this).parent().parent().parent().parent());
        });

        $('input.estimation').live('keyup', function(event) {
            event.stopPropagation();
            Scrumie.Task.changeProgress(event, this);
        });

        $('input.done').live('click', function(event) {
            event.stopPropagation();
        });

        $('input.done').live('change', function(event) {
            Scrumie.Task.save($(this).parent().parent()); 
            Scrumie.Story.recalculate($(this).parent().parent().parent().parent());
        });

        $('input.done').live('keyup', function(event) {
            event.stopPropagation();
            Scrumie.Task.changeProgress(event, this);
        });

        $('select.owner').live('change', function(event) {
            event.stopPropagation();
            Scrumie.Task.save($(this).parent().parent());
        });

        $('select.owner').live('click', function(event) {
            event.stopPropagation();
        });

        $('#tabs-backlog button.add_new_user_story').click(function(event) {
            var story = $('#newuserstory').find('table').clone();
            Scrumie.Story.add(story, 'backlog', function() {
                story.appendTo('div#detached'); 
            });
        });

        $('#tabs-board button.add_new_user_story').click(function(event) {
            var story = $('#newuserstory').find('table').clone();
            Scrumie.Story.add(story, 'sprint', function() {
                story.appendTo('div#story-container'); 
            });
        });

        $('div.task div.body[contenteditable=true]').live('click', function(event) {
            event.stopPropagation();
        });

        $('div.task div.body[contenteditable=false]').live('dblclick', function(event) {
            Scrumie.Task.edit($(this).parent());
        });

        $('button.color').live('click', function(event) {
            event.stopPropagation();
            $(this).parent().parent().find('div.body').css('background-color', $(this).attr('data-color'));
        });
    }());
});
</script>

<?php
function prepareTask(Task $task, $project) {

    if($task->estimation === null)
        $task->estimation = 1;

    if($task->done === null)
        $task->done = 0;

    if($task->body === null)
        $task->body = 'Double click to edit...';

    $owner = array('<option>Select owner...</option>');
    foreach($project->getUsers() as $userProject) {
        $user = $userProject->getUser();
        $selected = ($task->owner == $user->login) ? 'selected="selected"' : '';
        $owner[] = "<option $selected value='{$user->login}'>{$user->login}</option>";
    }

    $taskHelper = '
        <div id="%s" class="task draggable">
            <div class="body" style="background-color: %s" contenteditable="false">%s</div>
            <div class="status">
                <input title="Done" class="done noneditable" value="%s"/>/<input title="Estimation" class="estimation noneditable" value="%s"/>
                <select title="Owner" name="owner" class="owner">%s</select>
                <button data-color="#F79F81" class="color red noneditable"></button><button data-color="lightgreen" class="color green noneditable"></button><button data-color="lightblue" class="color blue noneditable"></button><button data-color="#FFFECB" class="color yellow noneditable"></button><button data-color="#ddd" class="color gray noneditable"></button>
                <img class="delete_task" src="http://cdn1.iconfinder.com/data/icons/uidesignicons/delete.png" title="Delete task" />
                <span class="confirm_delete"><em>Are you sure?:</em><button class="yes">Yes</button><button class="cancel">Cancel</button></span>
                <span style="display: inline-block; width: 2px;"></span>
            </div>
        </div>';

    return sprintf($taskHelper, $task->id, $task->color, $task->body, $task->done, $task->estimation, join('', $owner));
}


function prepareUserStory($story, $project) {
    $storyHtml = '
        <table class="user_story" data-storyid="%s">
        <tbody>
            <tr class="title">
                <td colspan="4">
                    <img class="icon detach" title="'.( ($story->active) ? 'Move to backlog' : 'Move to board').'" src="http://cdn3.iconfinder.com/data/icons/woothemesiconset/16/arrow_left.png"/>
                    <img class="icon add_new_task" onclick="Scrumie.Task.add($(\'#newtask\').find(\'div.task\'), $(this).parent().parent().parent().find(\'tr.board\').find(\'td.todo\'))" src="http://cdn2.iconfinder.com/data/icons/basicset/plus_16.png">
                    <img title="Delete user story" class="icon delete_user_story" onclick="Scrumie.Story.del($(this).parent().parent().parent().parent())" src="http://cdn2.iconfinder.com/data/icons/oxygen/16x16/actions/mail-delete.png"/>
                    <span class="user_story confirm_delete"> <em>Are you sure?:</em><button class="yes">Yes</button><button class="cancel">Cancel</button> </span>
                    <span class="name" ondblclick="Scrumie.Story.edit($(this).parent().parent().parent().parent())">%s</span>
                </td>
            </tr>
            <tr class="points">
                <td class="todo">'.$story->getTasks()->getTodo()->getDoneSum().'/'.($todoSum = $story->getTasks()->getTodo()->getEstimationSum()).'</td>
                <td class="inProgress">'.$story->getTasks()->getInProgress()->getDoneSum().'/'.($inProgressSum = $todoSum + $story->getTasks()->getInProgress()->getEstimationSum()).'</td>
                <td class="toVerify">'.$story->getTasks()->getToVerify()->getDoneSum().'/'.($toVerifySum = $inProgressSum + $story->getTasks()->getToVerify()->getEstimationSum()).'</td>
                <td class="done">'.$story->getTasks()->getDone()->getDoneSum().'/'.($toVerifySum + $story->getTasks()->getDone()->getEstimationSum()).'</td>
            </tr>
            <tr class="board">
                <td data-state="todo" class="todo droppable">%s</td>
                <td data-state="inProgress" class="inProgress droppable">%s</td>
                <td data-state="toVerify" class="toVerify droppable">%s</td>
                <td data-state="done" class="done droppable">%s</td>
            </tr>
            <tr><td colspan="4" style="height: 10px; border: 0;"></td></tr>
        </tbody>
        </table>
    ';

    if(count($story->getTasks())) {
        $todo = '';
        foreach($story->getTasks()->getTodo() as $task) {
            $todo .= prepareTask($task, $project);
        }

        $inProgress = '';
        foreach($story->getTasks()->getInProgress() as $task) {
            $inProgress .= prepareTask($task, $project);
        }

        $toVerify = '';
        foreach($story->getTasks()->getToVerify() as $task) {
            $toVerify .= prepareTask($task, $project);
        }

        $done = '';
        foreach($story->getTasks()->getDone() as $task) {
            $done .= prepareTask($task, $project);
        }
        return sprintf($storyHtml, $story->id, $story->name, $todo, $inProgress, $toVerify, $done);
    }
    else {
        return sprintf($storyHtml, $story->id, $story->name, null, null, null, null);
    }
}
?>
