<?php
function prepareTask(Task $task, $draggable = true) {

    if($task->estimation === null)
        $task->estimation = 1;

    if($task->done === null)
        $task->done = 0;

    $draggable = ($draggable) ? 'draggable' : '';

    $taskHelper = '
        <div id="%s" class="task round4 %s">
            <div class="editable body">%s</div>
            <span title="Estimation" class="estimation">%s</span>
            &nbsp;
            <span title="Done" class="done">%s</span>
            &nbsp;
            <span class="owner" title="Owner" style="float: right;">%s</span>
        </div>';

    return sprintf($taskHelper, $task->id, $draggable, $task->body, $task->estimation, $task->done, $task->owner);
}
?>

<div id="tabs">
    <ul>
        <li><a href="#tabs-home"><img src="http://cdn1.iconfinder.com/data/icons/gnomeicontheme/16x16/actions/redhat-home.png"></a></li>
        <?php if(isset($this->sprint)): ?>
        <li><a href="#tabs-board"><?= $this->sprint->name; ?></a></li>
        <li><a href="#tabs-burndownchart">Burn down chart</a></li>
        <?php endif ?>
        <?php if(isset($this->project)): ?>
        <li><a href="#tabs-backlog">Backlog</a></li>
        <?php endif ?>
        <li><a onclick="Scrumie.logout()">Logout</a></li>
    </ul>

    <div id="tabs-home" class="tabContent">
        <table class="home">
            <tr><th>Welcome!</th><td style="font-weight: bold; font-size: 18px;"><?= $this->user->login; ?>
            </td></tr>
            <tr>
                <th style="vertical-align: top">Projects:</th>
                <td>
                    <fieldset>
                        <legend>
                            <input id="new-project-name" type="text" placeholder="New project name">
                            <button title="Add new project" onclick="addNewProject()">+</button>
                            <button title="Untouch/Delete project.&#13;Project will be deleted when no others contributors are assigned to it, otherwise it will be untouch only from your account" onclick="deleteProject()">-</button>
                            <div id="importProject" title="If you already have some projects in Scrumie, you can import it easly to your account. Just enter project name and its password" style="display: none; padding: 5px;  border-radius: 4px; margin-left: 10px;">
                                Import:
                                <input placeholder="Project name" name="project" type="text">
                                <input placeholder="Project password" name="password" type="password">
                                <button style="margin-right: 10px;" onclick="importProject()">Import project</button>
                            </div>
                        </legend>
                        <div style="padding: 10px;">
                        <?php
                        $projects = array();
                        foreach($this->user->projects as $userProject) {
                            $project = $userProject->project;
                            $class = (isset($this->currentProjectId) && $project->id == $this->currentProjectId) ? 'selected' : '';
                            $projects[] = '<div onclick="Scrumie.Project.select('.$project->id.')" class="projectName '.$class.'">'.$project->name.'</div>';
                        }
                        echo join('', $projects);
                        ?>
                        </div>
                    </fieldset>
                </td>
            </tr>

            <?php if(isset($this->project)): ?>
            <tr><th style="vertical-align: top;" >Spints:</th>
                <td style="padding: 0">
                    <fieldset>
                        <legend>
                            <input id="new-sprint-name" type="text" placeholder="sprint name">
                            <button title="Add new sprint" onclick="Scrumie.Sprint.add($(this).parent().find('input').val())">+</button>
                        </legend>
                        <ul id="sprints-list">
                            <?php
                            foreach($this->project->sprints as $sprint) {
                                $edit = '<span onclick="Scrumie.Sprint.edit('.$sprint->id.')" class="ui-icon ui-icon-pencil round4 icon" title="Edit sprint name" ></span>';
                                $delete = '<span onclick="Scrumie.Sprint.del('.$sprint->id.')" class="ui-icon ui-icon-trash round4 icon" title="Delete" ></span>';

                                echo "<li data-sprintId='{$sprint->id}' class='sprint'><span onclick='Scrumie.Sprint.select({$sprint->id});' class='href' style='padding: 2px; margin-right: 10px;'>{$sprint->name}</span>$edit&nbsp;$delete</li>";
                            }
                            ?>
                        </ul>
                    </fieldset>
                </td>
            </tr>

            <tr><th style="vertical-align: top;">Contributors:</th>
                <td style="padding: 0">
                    <fieldset class="contributors">
                        <legend>
                        <input id="new-contributor-name" type="text" placeholder="username">
                        <button title="Add new contributor" onclick="addNewUser()">+</button>
                        </legend>
                        <blockquote>
                        <?php
                        $contributors = array();
                        foreach($this->project->users as $projectUser) {
                            $user = $projectUser->user;
                            if($user->email) {
                                $contributors[] = '<a href="mailto:'.$user->email.'">'.$user->login.'</a>';
                            } else {
                                $contributors[] = '<span>'.$user->login.'</span>';
                            }
                        }
                        echo join(', ', $contributors);
                        ?>
                        </blockquote>
                    </fieldset>
                </td>
            </tr>
            <?php endif ?>
        </table>
    </div>

    <?php if(isset($this->sprint)): ?>
    <div id="tabs-board" class="tabContent">
        <div class="helpers">
            <button onclick="Scrumie.Task.add($(this).find('div.task'), 'td#todo'); setEditable(); setDraggable(); ">+ Add new task
                <div id="" data-sprintId="<?= (isset($this->sprint)) ? $this->sprint->id : '';?>" class="task round4 draggable hidden">
                    <div class="editable body">Double click to edit...</div>
                    <span title="Estimation" class="estimation">1</span>
                    <span class="done">0</span>
                    <span class="owner" title="Owner" style="float: right;"></span>
                </div>
            </button>
        </div>
        <table id="board" class="round4">
            <tr>
                <th>
                    TODO
                    <div class="summary">
                        <span id="todo-sum-done">0</span>
                        /
                        <span id="todo-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    IN PROGRESS
                    <div class="summary">
                        <span id="inProgress-sum-done">0</span>
                        /
                        <span id="inProgress-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    COMMITED
                    <div class="summary">
                        <span id="commited-sum-done">0</span>
                        /
                        <span id="commited-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    READY FOR TEST
                    <div class="summary">
                        <span id="readyForTest-sum-done">0</span>
                        /
                        <span id="readyForTest-sum-estimation">0</span>
                    </div>
                </th>
                <th>
                    DONE
                    <div class="summary">
                        <span id="done-sum-done">0</span>
                        /
                        <span id="done-sum-estimation">0</span>
                    </div>
                </th>
            </tr>
            <tr>
                <td id="todo" class="droppable">
                <?php
                    foreach($this->sprint->tasks->getTodo() as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="inProgress" class="droppable">
                <?php
                    foreach($this->sprint->tasks->getInProgress() as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="commited" class="droppable">
                <?php
                    foreach($this->sprint->tasks->getCommited() as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="readyForTest" class="droppable">
                <?php
                    foreach($this->sprint->tasks->getReadyForTest() as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
                <td id="done" class="droppable">
                <?php
                    foreach($this->sprint->tasks->getDone() as $task) {
                        echo prepareTask($task);
                    }
                ?>
                </td>
            </tr>
        </table>
    </div>
    <?php endif ?>

    <?php if(isset($this->sprint)): ?>
    <div id="tabs-burndownchart" class="tabContent">
    <button onclick="reloadBtc()">Redraw</button>
    <div style="width: 90%" id="burndownchart-container"></div>
    <script>
        var chart;
        $(document).ready(function() {
           chart = new Highcharts.Chart({
              chart: {
                 renderTo: 'burndownchart-container'
              },
              xAxis: {
                categories: [<?= '"'.join('","', $this->sprint->tasks->getAllTasksUpdateDates('D/d/M')).'"'; ?>]
              },
              yAxis: {
                 title: {text: 'Estimation points'},
                 min: 0,
                 max: <?= $this->sprint->tasks->getEstimationSum() ?>,
              },
              title: {
                 text: 'Burndown chart'
              },
              tooltip: { formatter: function() { return this.y +' points' } },
              series: [{
                 name: 'Points left',
                 data: [<?= join(",", $this->sprint->getEstimationForEachSprintDate()) ?>],
                 marker: {
                    radius: 4
                 }
              }]
           });
        });

        function reloadBtc() {
            location.href = location.href.replace(/&tab.*/, '') + '&tab=2';
        }
    </script>
    </div>
    <?php endif ?>

    <?php if(isset($this->project)): ?>
    <div id="tabs-backlog" class="tabContent">
        <button onclick="addNewBacklogTask();">+ Add new task</button>
        <div class="sortable" id="detached">
            <?php
                 foreach($this->project->tasks->getDetached() as $task) {
                    echo prepareTask($task, false);
                }
            ?>
        </div>
    </div>
    <?php endif ?>

</div>

<!-- task context menu -->
<div class="contextMenu" id="taskMenu">
    <ul>
        <li id="task_estimate">Estimate</li>
        <li id="task_done">Set done</li>
        <li id="task_setOwner">Set owner</li>
        <li><hr/></li>
        <li id="task_attach">Move to sprint</li>
        <li id="task_detach">Move&nbsp;to&nbsp;backlog</li>
        <li><hr/></li>
        <li id="task_delete">Delete</li>
    </ul>
</div>

<script>
function setDraggable() {
    $(".draggable").draggable({
        stop: function(event, ui) {
            $(this).css('top', 0);
            $(this).css('left', 0);
        }
    });

    $(".draggable").css('cursor', 'move');
}

function setSortable() {
    $(".sortable").sortable({
        stop: function() {
            var order = new Array;
            $.each($(this).children('div.task'), function(index, element) {
                order[index] = $(element).attr('id');
            });

            $.post(Scrumie.uri('Project','reorderTask'), {'order': order}, function(data, status, Request) {
            });
        }
    });
}

function setEditable() {

    $.each($('.editable'), function(index, element) {
        $(element).unbind();
    });

    $('.task').contextMenu("taskMenu", {
        shadow: true, 
        menuStyle: {
            width: '150px'
        },
        onShowMenu: function(e, menu) {
            var parent = $(e.currentTarget).parent();
            if($(parent).attr('id') == 'detached') {
                $('#task_detach', menu).remove();
            }
            else {
                $('#task_attach', menu).remove();
            }

            return menu;
        },
        bindings: {
            'task_estimate': function(t) {
                var value = prompt('Please enter estimation value');

                if(value === null)
                    return;

                if( value.match(/[^0-9]+/) )
                    alert('Estimation must be number');
                else
                    $(t).children('span.estimation').html(value);

                saveTask(t);
            },
            'task_done': function(t) {
                var value = prompt('Please enter value');

                if(value === null)
                    return;

                if( value.match(/[^0-9]+/) )
                    alert('It must be number');
                else
                    $(t).children('span.done').html(value);

                saveTask(t);
            },
            'task_setOwner': function(t) {
                var value = prompt('Please enter onwer');

                if(value === null)
                    return;

                $(t).children('span.owner').html(value);

                saveTask(t);
            },
            'task_delete': function(t) {
                if (! confirm('Are you sure you want to delete this task') )
                    return;

                $.post(Scrumie.uri('Project','deleteTask'), {taskId: $(t).attr('id')}, function(data, status, Request) {
                        if(data)
                            $(t).remove();
                });
            },
            'task_attach': function(t) {
                var task = $(t).appendTo('td#todo');
                saveTask(task);
            },
            'task_detach': function(t) {
                var task = $(t).appendTo('div#detached');
                saveTask(task);
            },
        }
    });

    $.each($('.editable'), function(index, element) {
        $(element).dblclick(function() {
            $(this).parent().draggable('option', 'disabled', true);
            $(this).attr('contenteditable', true);
            $(this).parent().fadeTo('slow', 0.9);
            $(this).css('border', '2px solid red');
            $(this).focus();

            $(this).unbind('blur');
            $(this).unbind('focus');
            $(this).blur(function () {
                saveTask($(this).parent());
            });
            $(this).focus(function () {
                //edit
            });
        });
    });
}

function saveTask(task) {
    $(task).draggable('option', 'disabled', false);
    $(task).fadeTo('slow', 1);
    var content = $(task).children('div.editable');
    $(content).attr('contenteditable', false);
    $(content).css('border', '0');

    var params = {
        taskId: $(task).attr('id'),
        body: $(content).html(),
        estimation: $(task).children('span.estimation').html(),
        done: $(task).children('span.done').html(),
        owner: $(task).children('span.owner').html(),
        sprintId: $(task).attr('data-sprintId'),
        state: $(task).parent().attr('id')
    };

    $.post(Scrumie.uri('Project', 'saveTask'), params, function(data, status, Request) {
        if(data)
            $(task).attr('id', data)
        else
            alert('Problem with saving data');
    });

    updateSummary();
}

function addNewBacklogTask() {
    <?php
        $task = new Task;
        $task->estimation = 1;
        $task->done = 0;
        $task->body = 'Double click to edit...';
        $task->id = null;
        $task->owner = null;
    ?>
    var task = '<?= str_replace("\n", '' ,prepareTask($task, false)); ?>';
    $('#detached').append(task);
    setSortable();
    setEditable();
}

function addNewProject() {
    var name = $('#new-project-name').val();

    if(name == '') {
        alert('Project name can\'t be empty');
    }
    else {
        $.post(Scrumie.uri('Project', 'addProject'), {'name': name}, function(data, status, Request) {
            if(data === true) {
                window.location.reload();
            } else {
                alert(data.error);
            }
        });
    }
}

$(".droppable").droppable({
    drop: function(event,ui) {
        ui.helper.appendTo(this);
        setDraggable();
        saveTask(ui.helper);
    }
});

function updateSummary() {
    var summary = [];
    summary['todo'] = {all: 0, done: 0};
    summary['inProgress'] = {all: 0, done: 0};
    summary['commited'] = {all: 0, done: 0};
    summary['readyForTest'] = {all: 0, done: 0};
    summary['done'] = {all: 0, done: 0};

    $.each($('table#board td'), function(index,element) {
        var column = $(element).attr('id');

        var summaryEstimation = 0;
        $.each($(element).children('div.task').children('span.estimation'), function(i, e) {
            summaryEstimation += getAsNumber($(e).html());
        });

        var summaryDone = 0;
        $.each($(element).children('div.task').children('span.done'), function(i, e) {
            summaryDone += getAsNumber($(e).html());
        });

        summary[column].all = summaryEstimation;
        summary[column].done = summaryDone;

    });

    $('span#todo-sum-estimation').html(summary['todo'].all);
    $('span#todo-sum-done').html(summary['todo'].done);

    $('span#inProgress-sum-estimation').html(summary['todo'].all + summary['inProgress'].all);
    $('span#inProgress-sum-done').html(summary['inProgress'].done);
    
    $('span#commited-sum-estimation').html(summary['todo'].all + summary['inProgress'].all + summary['commited'].all);
    $('span#commited-sum-done').html(summary['commited'].done);

    $('span#readyForTest-sum-estimation').html(summary['todo'].all + summary['inProgress'].all + summary['commited'].all + summary['readyForTest'].all);
    $('span#readyForTest-sum-done').html(summary['readyForTest'].done);

    $('span#done-sum-estimation').html(summary['todo'].all + summary['inProgress'].all + summary['commited'].all + summary['readyForTest'].all + summary['done'].all);
    $('span#done-sum-done').html(summary['done'].done);
}

function addNewUser() {
    $.post(Scrumie.uri('Project','addUserToProject'), {
        username: $('#new-contributor-name').val()
    }, function(data, status, Request) {
        if(data === true) {
            window.location.href = Scrumie.uri('Board', 'project');
        } else {
            alert(data.error);
        }
    });
}

function deleteProject() {
    var project = $('.projectName.selected');
    if(project.length == 0) {
        alert('Select project you want to untouch');
        return;
    }
    $.post(Scrumie.uri('Project', 'deleteProject') , {id: $(project).attr('data-projectid')}, function(data, status, Request) {
        if(data === true) {
            window.location.href = Scrumie.uri('Board', 'index');
        } else {
            alert(data.error);
        }
    });
}

function getAsNumber(value) {
        if(isNaN(value))
            return 0;

        if(value == '')
            return 0;

        return parseFloat(value);
}

$(document).ready(function() {
    setDraggable();
    setEditable();
    setSortable();
    updateSummary();
});
</script>
