<style>
    .dialog {display: none;}
    input.text {width: 180px;}
</style>
<center>
<div id="loginDialog" class="dialog">
    <form id="loginForm" onsubmit="return false;">
    <table>
    <tr><td>Project:</td><td><input class="text" name="name" type="text"/></td></tr>
    <tr><td>Password:</td><td><input class="text" name="password" type="password"/></td></tr>
    <tr><td></td><td style="text-align: right"><input type="submit" value="Go!" /></td></tr>
    </table>
    <a href="javascript: showRegistryDialog();">+ New project</a> 
    <br/><small>You can also login to demo project as demo:demo</small>
    <br/><small><a href="https://github.com/nigro/Scrumie">http:://github.com/nigro/Scrumie</a></small>



    </form>

</div>

<div id="registryDialog" class="dialog">
    <form id="registryForm" onsubmit="return false;">
        <table>
            <tr><td>Name:</td><td><input class="text" name="name" type="text"/></td></tr>
            <tr><td>Password:</td><td><input class="text" name="password" type="password"/></td></tr>
            <tr><td>Repeat&nbsp;pwd:</td><td><input class="text" name="password2" type="password"/></td></tr>
            <tr><td></td><td style="text-align: right"><input type="submit" value="Create" /></td></tr>
        </table>
    </form>
</div>
</center>


<script>
$(document).ready(function() {
    showLoginDialog();

    $('div#registryDialog input[type|="submit"]').click(function() {
        var formData = $('form#registryForm').serializeArray();
        $.post('?controller=Project&action=registry', formData, function(data, textStatus, Request) {
            if(isset(data.error)) {
                alert(data.error)
            }
            else
                location.href = '?controller=Index';
        });

        return false;
    });

    $('div#loginDialog input[type|="submit"]').click(function() {
        var formData = $('form#loginForm').serializeArray();
        $.post('?controller=Project&action=login', formData, function(data, textStatus, Request) {
            if(data === true)
                location.href = '?controller=Board';
            else
                alert('Authorization failed');
        });

        return false;
    });
});

function showLoginDialog() {

    loginDialog = $( "#loginDialog" ).dialog({
        title: 'Login',
        closeOnEscape: false,
        draggable: false,
        resizable: false,
    });
}

function showRegistryDialog() {
    $( "#registryDialog" ).dialog({
        title: 'New project',
        closeOnEscape: true,
        draggable: false,
        resizable: false,
    });
}
</script>
